version: '3.7'

services:
  web:
    build: .
    image: portfolio
  celery:
    image: portfolio
    command: >
      celery -A portfolio worker
      -l info
      --pidfile=/var/run/celery/celeryworker.pid
    depends_on:
      - web
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:5.0-alpine
    ports:
      - "6380:6380"

volumes:
  postgres_data:
