version: '3.7'

services:
  web:
    restart: always
    build: .
    command: /bin/sh init-web.sh
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery:
    restart: always
    build: .
    command: >
      celery -A portfolio worker
      -l info
      --pidfile=/var/run/celery/celeryworker.pid
    volumes:
      - ./:/app/
    env_file:
      - ./.env.dev
    depends_on:
      - web
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=portfolio_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    restart: always
    image: redis:5.0-alpine
    ports:
      - 6379:6379

volumes:
  postgres_data:
