version: '3.7'

services:
  web:
    volumes:
      - ./:/app/
    depends_on:
      - db
      - redis
  celery:
    command: >
      celery -A portfolio worker
      -l info
      --pidfile=/var/run/celery/celeryworker.pid
    volumes:
      - ./:/app/
    depends_on:
      - web
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:5.0-alpine

volumes:
  postgres_data:
