version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: portfolio
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000 --workers=2
    volumes:
      - /var/web/portfolio/static:/staticfiles
      - /var/web/portfolio/media:/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    networks:
      - app
      - proxy
    restart: unless-stopped
  celery:
    image: portfolio
    command: >
      celery -A portfolio worker
      -l info
      --pidfile=/home/app/var/run/celery/celeryworker.pid
    env_file:
      - ./.env.prod
    networks:
      - app
      - proxy
  redis:
    command: ['redis-server', '/etc/redis/redis.conf']
    volumes:
      - redis_data:/var/libredis/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    networks:
      - app
    restart: always

volumes:
  redis_data:

networks:
  app:
  proxy:
    external:
      name: nginx-proxy
