version: '3.7'

services:
  web:
    volumes:
      - ./:/app/
    command: /bin/sh web.dev.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  celery:
    volumes:
      - ./:/app/
    env_file:
      - ./.env.dev
  db:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=portfolio_dev
