version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: portfolio
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  celery:
    image: portfolio
    command: >
      celery -A portfolio worker
      -l info
      --pidfile=/home/app/var/run/celery/celeryworker.pid
    env_file:
      - ./.env.prod
  db:
    env_file:
      - ./.env.prod
  redis:
    command: ['redis-server', '/etc/redis/redis.conf']
    volumes:
      - redis_data:/var/libredis/data
      - ./redis/redis.conf:/etc/redis/redis.conf
  nginx:
    image: nginx:1.16.1-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles
      - media_volume:/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  redis_data:
  static_volume:
  media_volume:
