version: '3'

services:
  web:
    build: .
    image: portfolio
  celery:
    image: portfolio
    command: >
      celery -A portfolio worker
      -l info
      --pidfile=/var/run/celery/celeryworker.pid
    depends_on:
      - web
  redis:
    image: redis:5.0-alpine
    ports:
      - "6380:6380"

volumes:
  postgres_data:
