version: '3.7'

services:
  web:
    build: .
    command: /bin/sh initweb.dev.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  celery:
    build: .
    env_file:
      - ./.env.dev
  db:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=portfolio_dev
  redis:
    ports:
      - 6379:6379
